"""
TopicManager — Gestión persistente de temas para episodios.

Guarda temas en topics.json por pod, con estado (pending, in_progress, completed).
Permite crear, listar, eliminar, y marcar temas como completados.
Funciona junto con TopicEngine (genera temas con IA) y EpisodeManager (crea episodios).
"""

import os
import json
from datetime import datetime
from typing import List, Dict, Any, Optional

import structlog

log = structlog.get_logger(__name__)


class TopicManager:
    """Manages topic lifecycle: generate → save → pick → complete."""

    def __init__(self, pod_dir: str):
        """
        Initialize TopicManager for a specific pod.

        Args:
            pod_dir: Path to the pod directory (e.g. pods/kids_story/).
        """
        self.pod_dir = pod_dir
        self.topics_file = os.path.join(pod_dir, "topics.json")
        self.topics = self._load()

    # ==========================================
    # PERSISTENCE
    # ==========================================

    def _load(self) -> Dict[str, Any]:
        """Load topics from JSON file, or create empty structure."""
        if os.path.exists(self.topics_file):
            with open(self.topics_file, "r", encoding="utf-8") as f:
                return json.load(f)
        return {"topics": []}

    def _save(self):
        """Persist topics to disk."""
        with open(self.topics_file, "w", encoding="utf-8") as f:
            json.dump(self.topics, f, indent=2, ensure_ascii=False)

    # ==========================================
    # CRUD
    # ==========================================

    def add_topics(self, topics_from_ai: List[Dict[str, Any]]) -> int:
        """
        Add topics generated by TopicEngine to the persistent store.

        Args:
            topics_from_ai: List of topic dicts from TopicEngine.generate_topics().

        Returns:
            Number of topics added (skips duplicates by title).
        """
        existing_titles = {t["title"].lower() for t in self.topics["topics"]}
        added = 0

        for topic in topics_from_ai:
            title = topic.get("title", "").strip()
            if not title or title.lower() in existing_titles:
                continue

            topic_entry = {
                "id": self._next_id(),
                "title": title,
                "description": topic.get("description", ""),
                "educational_value": topic.get("educational_value", ""),
                "references_episode": topic.get("references_episode"),
                "target_emotion": topic.get("target_emotion", ""),
                "status": "pending",
                "episode_id": None,
                "created_at": datetime.now().isoformat(),
                "completed_at": None,
            }
            self.topics["topics"].append(topic_entry)
            existing_titles.add(title.lower())
            added += 1

        self._save()
        return added

    def get_all(self) -> List[Dict[str, Any]]:
        """Get all topics."""
        return self.topics["topics"]

    def get_by_status(self, status: str) -> List[Dict[str, Any]]:
        """Get topics filtered by status (pending, in_progress, completed)."""
        return [t for t in self.topics["topics"] if t["status"] == status]

    def get_pending(self) -> List[Dict[str, Any]]:
        """Get topics that haven't been started yet."""
        return self.get_by_status("pending")

    def get_incomplete(self) -> List[Dict[str, Any]]:
        """Get topics that are in progress but not completed."""
        return self.get_by_status("in_progress")

    def get_by_id(self, topic_id: str) -> Optional[Dict[str, Any]]:
        """Find a topic by ID."""
        for t in self.topics["topics"]:
            if t["id"] == topic_id:
                return t
        return None

    def pick_next(self) -> Optional[Dict[str, Any]]:
        """
        Pick the next pending topic and mark it as in_progress.

        Returns:
            The topic dict, or None if no pending topics.
        """
        pending = self.get_pending()
        if not pending:
            return None

        topic = pending[0]
        topic["status"] = "in_progress"
        self._save()
        return topic

    def mark_in_progress(self, topic_id: str, episode_id: str = None):
        """Mark a topic as in progress, optionally linking to an episode."""
        topic = self.get_by_id(topic_id)
        if topic:
            topic["status"] = "in_progress"
            if episode_id:
                topic["episode_id"] = episode_id
            self._save()

    def mark_completed(self, topic_id: str, episode_id: str = None):
        """Mark a topic as completed."""
        topic = self.get_by_id(topic_id)
        if topic:
            topic["status"] = "completed"
            topic["completed_at"] = datetime.now().isoformat()
            if episode_id:
                topic["episode_id"] = episode_id
            self._save()

    def delete_topic(self, topic_id: str) -> bool:
        """
        Delete a topic by ID.

        Returns:
            True if deleted, False if not found.
        """
        before = len(self.topics["topics"])
        self.topics["topics"] = [
            t for t in self.topics["topics"] if t["id"] != topic_id
        ]
        if len(self.topics["topics"]) < before:
            self._save()
            return True
        return False

    # ==========================================
    # DISPLAY
    # ==========================================

    def print_topics_table(self, filter_status: str = None):
        """
        Print a formatted table of topics.

        Args:
            filter_status: Optional status filter (pending, in_progress, completed).
        """
        topics = self.get_by_status(filter_status) if filter_status else self.get_all()

        if not topics:
            status_msg = f" con estado '{filter_status}'" if filter_status else ""
            print(f"  No hay temas{status_msg}.")
            return

        status_icons = {
            "pending": "📝",
            "in_progress": "🔄",
            "completed": "✅",
        }

        print(f"\n  {'ID':<12} {'Estado':<4} {'Título':<45} {'Emoción'}")
        print(f"  {'─'*12} {'─'*4} {'─'*45} {'─'*15}")

        for t in topics:
            icon = status_icons.get(t["status"], "❓")
            title = t["title"][:43] + ".." if len(t["title"]) > 45 else t["title"]
            emotion = t.get("target_emotion", "")[:15]
            print(f"  {t['id']:<12} {icon}  {title:<45} {emotion}")

        # Summary
        total = len(self.get_all())
        pending = len(self.get_pending())
        completed = len(self.get_by_status("completed"))
        print(f"\n  Total: {total} | Pendientes: {pending} | Completados: {completed}")

    # ==========================================
    # HELPERS
    # ==========================================

    def _next_id(self) -> str:
        """Generate next topic ID (topic_001, topic_002, ...)."""
        existing = self.topics["topics"]
        if not existing:
            return "topic_001"

        # Find highest numeric ID
        max_num = 0
        for t in existing:
            tid = t.get("id", "")
            if tid.startswith("topic_"):
                try:
                    num = int(tid.split("_")[1])
                    max_num = max(max_num, num)
                except (ValueError, IndexError):
                    pass
        return f"topic_{max_num + 1:03d}"

    @property
    def count(self) -> int:
        """Total number of topics."""
        return len(self.topics["topics"])

    @property
    def pending_count(self) -> int:
        """Number of pending topics."""
        return len(self.get_pending())
